pimcore:
    assets:
        video:
            thumbnails:
                definitions:
                    small:
                        items:
                            -
                                method: resize
                                arguments:
                                    width: 320
                                    height: 240
                                    displayfield-2108-inputEl: '<small style=''color: red;''>width and height must be an even number</small>'
                        medias: {  }
                        name: small
                        description: 'Small video '
                        group: ''
                        videoBitrate: 400
                        audioBitrate: 128
                        modificationDate: 1657716554
                        creationDate: 1657714084
